### ISSUE TITLE
Remote SSH backdoor

### ISSUE THREAD

**Issue by terrorobe** [rucarrol/FortiFacts#5]
Not sure if silently introducing and removing a SSH backdoor is worth a mention:

https://twitter.com/pentestit/status/686761604512268288

**Comment by rucarrol** [comment]
Created [pull request](https://github.com/rucarrol/FortiFacts/pull/6 ) from branch now_with_added_backdoor and merged. 

Ok to close?

**Comment by terrorobe** [comment]
Absolutely, thanks :)
